pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('mle-template')
        LC_ALL   = "en_US.UTF-8"
        LANG     = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {

        stage('Login') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Pull image') {
            steps {
                sh 'docker pull ddulaev/lab2:latest'
            }
        }

        stage('Run container and functional tests') {
            steps{
                sh 'docker run --name lab2 -p 80:5556 -d ddulaev/lab2:latest python -m src.func_test.api_test'
            }
        }
	}

    post {
        always {
            sh 'docker stop lab2 && docker remove lab2 && docker logout'
        }
    }
}
