pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('mle-template')
        LC_ALL   = "en_US.UTF-8"
        LANG     = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {

        stage('Login') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Pull image') {
            steps {
                sh 'docker pull ddulaev/mle-template:latest'
            }
        }

//         stage('Run container') {
//             steps{
//                 sh 'docker run --name mle-template -p 80:5556 -d ddulaev/mle-template:latest'
//             }
//         }

        stage('Run functional tests') {
            steps{
                sh 'docker run --name mle-template -p 80:5556 -d ddulaev/mle-template:latest python -m src.func_test.api_test'
            }
        }
	}

    post {
        always {
            sh 'docker stop mle-template && docker remove mle-template && docker logout'
        }
    }
}
