pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('mle-template')
        LC_ALL   = "en_US.UTF-8"
        LANG     = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Clone github repository') {
            steps {
                cleanWs()
                sh 'git clone -b main https://github.com/Timoniche/BigDataLab1.git'
			}
		}

        stage('Checkout repo dir') {
            steps {
                sh 'cd BigDataLab1 && dir'
			}
	    }

        stage('Login') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Building docker') {
            steps {
                sh 'cd BigDataLab1 && docker compose build'
            }
        }
        stage('Create and run docker container') {
            steps {
                sh 'cd BigDataLab1 && docker compose up -d'
            }
        }

        stage('Checkout coverage report') {
            steps{
                dir("BigDataLab1") {
                    sh 'docker compose logs -t --tail 10'
                }
            }
        }

        stage('Push') {
            steps {
                sh 'docker push ddulaev/mle-template:latest'
            }
        }
	}

    post {
        always {
            sh 'docker logout'
        }
    }
}
